// Problem Link: https://leetcode.com/problems/smallest-string-with-a-given-numeric-value/

// Time Complexity: O(n)
// Space Complexity: O(1)

/*
concept, insert as large as possible value in the end, so that as small as possible value can be inserted in the front
test cases are made in such a way that we dont need to bother about if given score can be generated by the length of string or not
thus making the greedy approoach easy
*/

class Solution
{
public:
    string getSmallestString(int n, int k)
    {
        string ans(n, 'a');
        k -= n;
        while (k > 0)
        {
            n--;
            ans[n] = min(25 + 'a', k + 'a');
            k -= min(25, k);
        }
        return ans;
    }
};